export interface User {
  type?: string;
  id?: number;
  etapa?: string;
  nome?: string;
  cep?: string | null;
  endereco?: string | null;
  estado?: string | null;
  cidade?: string | null;
  bairro?: string | null;
  profissao?: string;
  comprovante_endereco?: string | null;
  complemento?: string | null;
  numero?: string | null;
  nascimento?: string;
  whatsapp?: string;
  whatsapp2?: string | null;
  cpf?: string;
  foto_perfil_app?: string | null;
  foto_perfil_app2?: string | null;
  ganhos_app?: number | null;
  foto_docveiculo?: string | null;
  foto_veiculo?: string | null;
  comprovante_comercio?: string | null;
  extrato_bancario?: string | null;
  tipo_comercio?: string | null;
  descricao_comercio?: string | null;
  video_comercio?: string | null;
  video_fachada?: string | null;
  video_perfil_app?: string | null;
  chave?: string | null;
  pix?: string | null;
  email?: string | null;
  status?: string;
  data_retentativa?: string | null;
  divergencias?: string | null;
  url_reconhecimento?: string | null;
  face?: string | null;
  validacoes?: string | null;
  motivo_recusa?: string | null;
  foto_frente_doc?: string | null;
  foto_verso_doc?: string | null;
  criado?: string;
  data_finalizado?: string | null;
  observacoes?: string | null;
  termos?: number;
  signature?: string | null;
  mei?: string | null;
  tem_cnpj?: string | null;
  fachada?: string | null;
  interior?: string | null;
  data_divergencia?: string | null;
  placa?: string | null;
  gestor?: string | null;
  repescagem?: string | null;
  aplicativo?: string | null;
  chamada_video?: number;
  data_preaprovacao?: string | null;
  erro?: string | null;
  fbp?: string | null;
  fbc?: string | null;
  fbclid?: string | null;
  info_start?: string;
  info_end?: string | null;
  ip?: string;
  uuid?: string;
  umbler_contact_id?: string | null;
  cnpj?: string | null;
  cnpj_info?: string | null;
  open_finance_attempts?: number;
  user_agent?: string | null;
  codigo_afiliado_ref?: string | null;
  primeiro_login_otp_em?: string | null;
  aprovado_palenca?: number;
  palenca_status?: string | null;
  token?: string | null;
  password?: string | null;
  afiliado?: string | null;
}
