export const documentDisplayNames: Record<string, string> = {
  phone: "Novo telefone",
  telefone: "Novo telefone",
  celular: "Novo telefone",
  whatsapp: "Novo telefone",
  comprovante_endereco: "Comprovante de endereço",
  foto_perfil_app: "Perfil no App de Corridas",
  foto_perfil_app2: "Perfil em Outro App",
  foto_docveiculo: "Documento do Veículo",
  foto_veiculo: "Foto do Veículo",
  video_comercio: "Vídeo do Comércio",
  ganhos_app: "Relatório de Ganhos",
  foto_frente_doc: "Foto Frente do Documento",
  foto_verso_doc: "Foto do QRCode do Documento",
  fachada: "Foto da Fachada",
  video_fachada: "Vídeo da Fachada",
  video_interior: "Vídeo do Interior",
  mei: "Certificado de MEI",
  face: "Reconhecimento Facial",
  video_perfil_app: "Vídeo do Perfil no App",
  openfinance: "Open Finance",
};
